sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.108.100
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

minio:
  oss:
    endpoint: http://192.168.108.100:9000
    access-key: sN7vUz9jJwwyis5iTpxO
    secret-key: fab1yPqRJdYgwAIf3twBvcmcpYdYoaswfwjEORGl
    bucket-name: sky-take-out